import { SessionId, SessionPlan } from "./types"

/**
 * Protocolo aposentado da preparação para o campeonato de flag football
 * (18/07 a 15/08/2026). Não entra em nenhum programa ativo nem no seed de
 * templates — vive aqui só para que os treinos já registrados continuem
 * exibindo título, exercícios e prescrição no Histórico.
 */
export const LEGACY_SESSIONS: SessionPlan[] = [
  {
    id: "competitionLower",
    title: "A · Inferior + Potência",
    subtitle: "Sessão-chave · longe do campo pesado",
    weekday: 0,
    duration: "~55–65 min",
    kind: "lift",
    accent: "gold",
    description:
      "Faça com as pernas frescas e, idealmente, a 48 h de sprint, cortes ou coletivo forte. Explosivos sempre vêm primeiro.",
    exercises: [
      {
        id: "box-jump",
        name: "Salto na caixa",
        nameEn: "Box Jump",
        muscleGroup: "Quadríceps",
        sets: 4,
        repsMin: 3,
        repsMax: 3,
        unit: "reps",
        rest: "2 min",
        note:
          "Escolha 1 explosivo: salto na caixa, salto horizontal ou swing 4×6. Aterrisse leve; descanso total e intenção máxima.",
      },
      {
        id: "squat",
        name: "Agachamento livre",
        nameEn: "Back Squat",
        muscleGroup: "Quadríceps",
        sets: 3,
        repsMin: 4,
        repsMax: 5,
        unit: "reps",
        rest: "2–3 min",
        note: "3–4 séries @ 85–90 kg · RIR 2–3 · manutenção de força, sem grind e sem PR.",
      },
      {
        id: "rdl",
        name: "Terra romeno (RDL)",
        nameEn: "Romanian Deadlift",
        muscleGroup: "Posterior/Glúteo",
        sets: 3,
        repsMin: 6,
        repsMax: 8,
        unit: "reps",
        rest: "2 min",
        note: "55–70 kg · RIR 2 · excêntrico controlado para proteger os isquios no sprint.",
      },
      {
        id: "bulgarian",
        name: "Agachamento búlgaro / afundo",
        nameEn: "Bulgarian Split Squat / Lunge",
        muscleGroup: "Quadríceps",
        sets: 2,
        repsMin: 6,
        repsMax: 8,
        unit: "reps",
        rest: "90 s",
        note: "2–3 séries por perna · estabilidade unilateral para cortar e desacelerar.",
      },
      {
        id: "calf",
        name: "Panturrilha em pé",
        nameEn: "Standing Calf Raise",
        muscleGroup: "Panturrilha",
        sets: 3,
        repsMin: 8,
        repsMax: 12,
        unit: "reps",
        rest: "60–90 s",
        note: "Pausa de 1 s embaixo · resiliência de Aquiles para sprint e corte.",
      },
      {
        id: "nordic",
        name: "Nórdico de isquios",
        nameEn: "Nordic Hamstring Curl",
        muscleGroup: "Posterior/Glúteo",
        sets: 2,
        repsMin: 3,
        repsMax: 5,
        unit: "reps",
        rest: "2 min",
        note: "Progrida devagar. Alternativa: mesa flexora 2×8–10. Pare antes de perder o controle.",
      },
    ],
  },
  {
    id: "competitionUpper",
    title: "B · Superiores + Core",
    subtitle: "Baixo custo para as pernas · flexível",
    weekday: 0,
    duration: "~50–60 min",
    kind: "lift",
    accent: "gold",
    description:
      "Pode entrar perto de um dia de campo porque gera pouco cansaço nas pernas. Todos os compostos ficam longe da falha.",
    exercises: [
      {
        id: "bench",
        name: "Supino reto com barra",
        nameEn: "Barbell Bench Press",
        muscleGroup: "Peito",
        sets: 3,
        repsMin: 4,
        repsMax: 6,
        unit: "reps",
        rest: "2–3 min",
        note: "3–4 séries @ 55–60 kg · RIR 2 · manutenção de força, sem buscar PR.",
      },
      {
        id: "row",
        name: "Remada",
        nameEn: "Row",
        muscleGroup: "Costas",
        sets: 3,
        repsMin: 6,
        repsMax: 10,
        unit: "reps",
        rest: "90 s",
        note: "Tronco firme, sem roubo.",
      },
      {
        id: "ohp",
        name: "Desenvolvimento com barra ou halteres",
        nameEn: "Overhead Press",
        muscleGroup: "Ombro",
        sets: 3,
        repsMin: 5,
        repsMax: 8,
        unit: "reps",
        rest: "2 min",
        note: "Manter a força do ombro é prioridade; deixe 2–3 repetições na reserva.",
      },
      {
        id: "pulldown",
        name: "Puxada alta / barra fixa",
        nameEn: "Lat Pulldown / Pull-up",
        muscleGroup: "Costas",
        sets: 2,
        repsMin: 8,
        repsMax: 10,
        unit: "reps",
        rest: "90 s",
        note: "2–3 séries, técnica limpa.",
      },
      {
        id: "facepull",
        name: "Face pull",
        nameEn: "Face Pull",
        muscleGroup: "Ombro",
        sets: 3,
        repsMin: 15,
        repsMax: 15,
        unit: "reps",
        rest: "60 s",
        note: "Saúde de ombro e deltoide posterior.",
      },
      {
        id: "pallof",
        name: "Pallof press",
        nameEn: "Pallof Press",
        muscleGroup: "Core",
        sets: 3,
        repsMin: 10,
        repsMax: 10,
        unit: "reps",
        rest: "60 s",
        note: "10 repetições por lado · anti-rotação para sprint e mudança de direção.",
      },
      {
        id: "dead-bug",
        name: "Dead bug / prancha",
        nameEn: "Dead Bug / Plank",
        muscleGroup: "Core",
        sets: 3,
        repsMin: 8,
        repsMax: 12,
        unit: "reps",
        rest: "60 s",
        note: "Escolha um. No dead bug, conte por lado; na prancha, troque para 30–45 s.",
      },
    ],
  },
  {
    id: "competitionPower",
    title: "C · Potência Full-Body",
    subtitle: "Opcional · somente se estiver fresco",
    weekday: 0,
    duration: "~35–45 min",
    kind: "lift",
    accent: "gold",
    description:
      "É a primeira sessão a sair de uma semana puxada. Se estiver cansado do campo, faça mobilidade + 25 min de Zona 2 ou descanse.",
    exercises: [
      {
        id: "medball-slam",
        name: "Slam com medicine ball",
        nameEn: "Medicine Ball Slam",
        muscleGroup: "Core",
        sets: 3,
        repsMin: 5,
        repsMax: 5,
        unit: "reps",
        rest: "90 s",
        note: "Intenção máxima; encerre a série se a velocidade cair.",
      },
      {
        id: "medball-rotation",
        name: "Arremesso rotacional com medicine ball",
        nameEn: "Rotational Medicine Ball Throw",
        muscleGroup: "Core",
        sets: 3,
        repsMin: 5,
        repsMax: 5,
        unit: "reps",
        rest: "90 s",
        note: "5 por lado · potência de tronco para mudança de direção.",
      },
      {
        id: "kettlebell-swing",
        name: "Kettlebell swing / trenó",
        nameEn: "Kettlebell Swing / Sled Push",
        muscleGroup: "Posterior/Glúteo",
        sets: 3,
        repsMin: 8,
        repsMax: 8,
        unit: "reps",
        rest: "90 s",
        note: "Alternativa: 3–4 empurrões de trenó. Potência de quadril com baixo impacto.",
      },
      {
        id: "farmer-carry",
        name: "Farmer carry",
        nameEn: "Farmer Carry",
        muscleGroup: "Core",
        sets: 3,
        repsMin: 30,
        repsMax: 40,
        unit: "seconds",
        rest: "90 s",
        note: "3–4 passadas · postura alta, core e pegada firmes.",
      },
      {
        id: "copenhagen",
        name: "Prancha Copenhagen",
        nameEn: "Copenhagen Plank",
        muscleGroup: "Core",
        sets: 2,
        repsMin: 20,
        repsMax: 30,
        unit: "seconds",
        rest: "60 s",
        note: "Por lado · prehab de adutor. Sem dor na virilha.",
      },
      {
        id: "ankle-mobility",
        name: "Mobilidade de tornozelo",
        nameEn: "Ankle Mobility",
        muscleGroup: "Panturrilha",
        sets: 2,
        repsMin: 10,
        repsMax: 12,
        unit: "reps",
        rest: "30 s",
        note: "Movimento controlado, sem tirar o calcanhar do chão.",
      },
    ],
  },
  {
    id: "competitionZ2",
    title: "Zona 2 · Competição",
    subtitle: "Recuperação ativa e base aeróbica",
    weekday: 0,
    duration: "20–30 min",
    kind: "cardio",
    accent: "zone",
    cardioTarget: {
      min: 20,
      max: 30,
      defaultMinutes: 25,
      bpmMin: 125,
      bpmMax: 140,
    },
    description:
      "Bike ou esteira inclinada em ritmo de conversa, FC 125–140. Meta semanal: 60–90 min; zero HIIT na academia. Se o campo já foi pesado, pode pular.",
    exercises: [],
  },
]

const LEGACY_SESSION_IDS = new Set<SessionId>(
  LEGACY_SESSIONS.map((session) => session.id)
)

/** Registro pertence a um protocolo aposentado (marcado como tal no Histórico). */
export function isLegacySession(sessionId: SessionId): boolean {
  return LEGACY_SESSION_IDS.has(sessionId)
}
